import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const exodusSans = localFont({
  src: "./fonts/EudoxusSans-Bold.woff",
  variable: "--font-exodus-sans",
  weight: "100 900",
});
const interSans = localFont({
  src: "./fonts/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${exodusSans.variable} antialiased`}>
        <div id="root" className="flex flex-col px-[32px]">
          {children}
        </div>
      </body>
    </html>
  );
}
